### ISSUE TITLE
Call projects based on their status

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/flux-projects#6]
It would be nice to have a command for each status and when used, it calls all of the projects with that status.

Eg 

```
!open
```

Calls all of the open projects. 

These should be for admin only.

**Comment by connorhsm** [comment]
@KipCrossing Should the required role be the server admin or the newly created flux vetted role?

**Comment by KipCrossing** [comment]
Probably a new role. Do you think the role will be used elsewhere in the bot?

**Comment by BenBallingall** [comment]
aah, you beat me to it.

was gonna say, that's probably just Server Admin tbh. I imagine it's not something we'll need done often, but will be needed for housekeeping channels.

for 'status' (open, active, closed etc.) anyway - if we went deeper and had callable by Objective, Data, Project Type, we might need to give it to Flux Vetted as well.

**Comment by connorhsm** [comment]
I’ll go with server admin then. Simple to change later.

**Comment by KipCrossing** [comment]
The concept is turning into filters if we add other categories. Perhaps a `!filter` pre-phrase? I'll leave the UI design up to you @connorhsm though.

**Comment by connorhsm** [comment]
Is that filtering by categories or by terms within a category? Might be worth it's own issue.

**Comment by connorhsm** [comment]
Completed implementation of a `!filter` command. It will be live by the time you're reading this.
This implements the ability to display all projects, grouped by status with variable levels of detail included.

Usage: `!filter [status] [detail]`

Valid statuses:
- active
- open
- done
- blocked
- "out of scope" (quotes required due to spaces)

Valid levels of detail: (Followed by the details additionally included, if the information is avaliable.)
- short
  - Objective colour
  - Leader
  - Title
  - Description
  - Project ID
  - Official status
- long
  - Objective
  - Completion date
  - Status
- longer
  - Resources
  - Outcomes
  - Deliverables

Using the command without any arguments will show all projects with the `active` status at the level of detail of `short`.
To display the same projects as default usage, but using arguments is done so like `!filter active short`.

I've done a fair amount of testing through the day, caught many cases that cause an issue and handled them. I'm sure there are bound to be more, please open a bug report issue in that case.

**Comment by KipCrossing** [comment]
Nice work!
